<?php

namespace App\Enums;

enum EntityFieldType: string
{
    case Checkbox = 'checkbox';
    case String = 'string';
    case Select = 'select';
    case IntegerNumber = 'integer';
    case DecimalNumber = 'decimal';
    case Textarea = 'textarea';
    case RichText = 'richtext';
    case Relation = 'relation';
    case Date = 'date';
    case Time = 'time';
    case DateTime = 'datetime';
    case ColorPicker = 'color';
    case Code = 'code';

    public function label(): string
    {
        return match ($this) {
            self::Checkbox => 'Checkbox',
            self::String => 'Stringa',
            self::Select => 'Select',
            self::IntegerNumber => 'Numero intero',
            self::DecimalNumber => 'Numero decimale',
            self::Textarea => 'Textarea',
            self::RichText => 'Rich text',
            self::Relation => 'Relazione',
            self::Date => 'Data',
            self::Time => 'Ora',
            self::DateTime => 'Data e ora',
            self::ColorPicker => 'Color picker',
            self::Code => 'Codice',
        };
    }

    /**
     * Whether this field type stores a set of selectable choices
     * (in entity_fields.options).
     */
    public function hasOptions(): bool
    {
        return $this === self::Select;
    }

    /**
     * Whether this field type points at another entity/model record
     * (relation_target_type/relation_target on entity_fields).
     */
    public function isRelation(): bool
    {
        return $this === self::Relation;
    }

    /**
     * Whether this field's value is generated by the system (never
     * submitted by the user, excluded from record validation/forms).
     */
    public function isGenerated(): bool
    {
        return $this === self::Code;
    }

    /**
     * @return array<string, string>
     */
    public static function options(): array
    {
        return collect(self::cases())->mapWithKeys(fn (self $type) => [$type->value => $type->label()])->all();
    }
}
